workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test

build_windows:
  stage: build
  tags:
    - windows
  script:
    - Remove-Item build -Force  -Recurse -ErrorAction SilentlyContinue
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .
  artifacts:
    paths:
      - build

test_windows:
  stage: test
  tags:
    - windows
  script:
    - cd build
    - ctest
  needs: ["build_windows"]

build_linux:
  stage: build
  tags:
    - linux
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
    - ninja
  artifacts:
    paths:
      - build

test_linux:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - ctest
  needs: ["build_linux"]
