# workflow:
#   rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
#      when: never
#    - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test

nightly_windows:
  only:
    - schedules
  tags:
    - windows
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
    - ninja
    - ctest --output-on-failure

nightly_linux:
  image: ubuntu:lidar_dev
  only:
    - schedules
  tags:
    - linux
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
    - ninja
    - ctest --output-on-failure

build_windows:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  stage: build
  tags:
    - windows
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -GNinja ..
    - ninja
    - ctest --output-on-failure

build_linux:
  image: ubuntu:lidar_dev
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  stage: build
  tags:
    - linux
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
    - ninja
    - ctest --output-on-failure
