# workflow:
#   rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
#      when: never
#    - if: '$CI_COMMIT_BRANCH'

stages:
  - build

merge_build_linux:
  image: onet/visionet:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  stage: build
  tags:
    - linux
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa -p 2222 192.168.10.1 >> ~/.ssh/known_hosts
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
    - ninja -j 12
    - ctest --output-on-failure
