/**************************************************************************
 * @file:  UdpTests.cpp
 * @brief:
 *
 * Copyright (c) 2021 O-Net Technologies (Group) Limited.
**************************************************************************/

#include <gtest/gtest.h>

#include <network/UdpClient.h>
#include <network/UdpServer.h>

using namespace cppbase;

uint16_t port{1234};
uint16_t specified_port{2368};

TEST(UDPTests, UDPServerClient)
{
    network::Init();
    uint16_t conn_port = 5656;

    auto udp_server = std::make_shared<UdpServer>(port);
    udp_server->Start([udp_server,&conn_port](uint8_t* buffer, uint32_t bufsz, udp::endpoint& endpoint) {
        static char text[] = "hello";
        EXPECT_EQ(strlen(text), bufsz);
        EXPECT_STREQ(reinterpret_cast<char*>(buffer), text);
        auto ret = udp_server->Send(buffer, bufsz, endpoint);
        conn_port = endpoint.port();
        EXPECT_EQ(strlen(text), ret);
    });

    // Use the port generated by protocol randomly
    auto udp_client = std::make_shared<UdpClient>();
    EXPECT_TRUE(udp_client->Connect("127.0.0.1", port));
    std::string msg = "hello";
    auto ret = udp_client->Send(reinterpret_cast<const uint8_t*>(msg.c_str()), msg.length());
    EXPECT_EQ(msg.length(), ret);
    uint8_t buf[256] = {0};
    ret = udp_client->Receive(buf, 256);
    EXPECT_EQ(msg.length(), ret);
    EXPECT_STREQ(reinterpret_cast<char*>(buf), msg.c_str());

    // Use the specified port
    udp_client = std::make_shared<UdpClient>(specified_port);
    EXPECT_TRUE(udp_client->Connect("127.0.0.1", port));
    msg = "hello";
    ret = udp_client->Send(reinterpret_cast<const uint8_t*>(msg.c_str()), msg.length());
    EXPECT_EQ(msg.length(), ret);
    ret = udp_client->Receive(buf, 256);
    EXPECT_EQ(msg.length(), ret);
    EXPECT_STREQ(reinterpret_cast<char*>(buf), msg.c_str());
    EXPECT_EQ(conn_port, specified_port);

    network::Terminate();
}
